### ISSUE TITLE
Please cut a new release asap!

### ISSUE THREAD

**Issue by lancecarlson** [jshttp/proxy-addr#13]
https://github.com/whitequark/ipaddr.js/issues/89

**Comment by dougwilson** [comment]
I am currently traveling, but will definately look into this when I can in a few hours.

**Comment by dougwilson** [comment]
I'm going to close this because I'll release once there is something to actually release. The PR you made is waiting for you to update it, and once done & merged there would be a release, jut like any other change. There is no point in an extra issue for this.
