### ISSUE TITLE
Trust IP not returned boolean result.

### ISSUE THREAD

**Issue by rudiantotiofan** [jshttp/proxy-addr#17]
Hi, i want to ask, is the result of :
proxyaddr(req, function (addr) { return addr === '127.0.0.1' })
is boolean type ? cause the result i get is ip client, not true or false.

Thankss.

**Comment by dougwilson** [comment]
https://github.com/jshttp/proxy-addr/blob/master/README.md#proxyaddrreq-trust

> Return the address of the request, using the given trust parameter.

It is documented to return the address, not true/false.
