### ISSUE TITLE
Returned Function Parameter Count From compile()

### ISSUE THREAD

**Issue by ndunks** [jshttp/proxy-addr#22]
In this code is calling trust with two arguments:

https://github.com/jshttp/proxy-addr/blob/1cdd2f78e0fcc23ceae4723e6b837345c2499772/index.js#L69

But if look on the returned function from `compile()` -> `compileTrust()` -> `trustSingle/Multi()`, its just using one argument.

https://github.com/jshttp/proxy-addr/blob/1cdd2f78e0fcc23ceae4723e6b837345c2499772/index.js#L307

My question is, what the second parameter is used for? is safe to ignore that? 

I can create PR to remove that if needed.

**Comment by dougwilson** [comment]
Compile is not called if the user supplies a trust function, and thay user-defined function can use the second parameter to make trust decisions.

**Comment by dougwilson** [comment]
See the second example in the readme https://github.com/jshttp/proxy-addr#proxyaddrreq-trust

**Comment by ndunks** [comment]
Nope, just clarify. In internal proxy-addr is calling trust function with only one argument, right? and in user-defined function trust function "may" called with second argument? So, I think the second parameter is optional. This not affect with your repo, but I will make PR to typescript definition [repo](https://www.npmjs.com/package/@types/proxy-addr), because in that definition the the second parameter cannot be omitted even Im not use it.

**Comment by dougwilson** [comment]
I'm not sure what you are saying, exactly. Internally, this module will _always_ provide two arguments to the given `trust` function: the address and the index of that address. It expects a boolean to be returned to indicate if that address is trusted or not.

The result from the `compile` export of this module is meant to be used as the input to the `trust` argument, as it will return a function that matches that signature that is expected for the `trust` function so you can optimize if needed.

I hope that helps.
