### ISSUE TITLE
Add ipv6 mapped ipv4 addresses to built in ip ranges

### ISSUE THREAD

**Issue by wondersd** [jshttp/proxy-addr#24]
Been using `uniquelocal` as a `trust proxy` for expressjs to ignore rfc1918 addresses that trusted proxies are deployed into to get to the true client up.

All had been working well with this until ipv4 ips started being prefixed with `::ffff:` e.g. `::ffff:10.2.3.4`. Some cursory research suggest that these are ipv6 mapped ipv4 ips when running in an ipv6 complaint network.

https://stackoverflow.com/questions/29411551/express-js-req-ip-is-returning-ffff127-0-0-1

Given that it would seem to make sense to include these in the built in sets of `uniquelocal`, `loopback`, and `linklocal`

```
var IP_RANGES = {
  linklocal: ['169.254.0.0/16', '::ffff:169.254.0.0/16', 'fe80::/10'],
  loopback: ['127.0.0.1/8', '::ffff:127.0.0.1/8', '::1/128'],
  uniquelocal: ['10.0.0.0/8', '::ffff:10.0.0.0/8', '172.16.0.0/12', '::ffff:172.16.0.0/12', '192.168.0.0/16', '::ffff:192.168.0.0/16', 'fc00::/7']
}
```

**Comment by wesleytodd** [comment]
Ah interesting. Yeah this must not be very common for it to not have come up as a suggestion here for this long. That said, seems likely to be a good addition. Would you mind opening this as a PR so we can discuss details in that form as necessary?
