### ISSUE TITLE
proxy-addr returning ::ffff:127.0.0.1 for my local IP

### ISSUE THREAD

**Issue by cmeans** [jshttp/proxy-addr#4]
Seems like proxy-addr is combining my IPv6 and IPv4 IP addresses when reporting what my IP is.

Is this intentional behavior?

````javascript
    var proxyAddr = require('proxy-addr');

    //...
    req.ip = 
        proxyAddr(
            req, 
            'loopback');
````

I'm using restify, on Win7, debugging within MyEclipse if that makes a difference.

**Comment by dougwilson** [comment]
This is how Node.js 0.12+ functions. You can find the bug report on Node.js at https://github.com/nodejs/node-v0.x-archive/issues/9195 The value we are giving you is just coming from `req.connection.remoteAddress`.
