### ISSUE TITLE
Upgrade to ipaddr 1.0.5 - Fix error with IP undefined

### ISSUE THREAD

**Issue by EnzoMartin** [jshttp/proxy-addr#6]
Fixes breaking issue when undefined is passed through to the `ipaddr` `isValid` method as seen here:

https://github.com/whitequark/ipaddr.js/commit/bebf6ea473b35ac45238804ff0533157f8986266

**Comment by dougwilson** [comment]
Awesome, thanks for the report! I added a couple tests as well so if this breaks again we'll know :) I'm going to publish to npm is just a bit.

**Comment by dougwilson** [comment]
Published to npm as 1.0.10

**Comment by EnzoMartin** [comment]
Good to hear, thanks!
