### ISSUE TITLE
Port support?

### ISSUE THREAD

**Issue by silverwind** [jshttp/proxy-addr#8]
Are you planning to add source port support to this module?

Source ports are necessary to uniquely identify users behind NATs and can be obtained from `X-Forwarded-Port` and friends.

**Comment by dougwilson** [comment]
There aren't any plans, but this would indicate a request for it to be added, which I can do, or you're welcome to work on a PR in the mean time :)

**Comment by silverwind** [comment]
I'd certainly be interested in contributing. I think we have to switch to a header parser that supports ports like [forwarded-for](https://github.com/primus/forwarded-for), would that be okay for you?

**Comment by dougwilson** [comment]
No, just PR into our dependency, `forwarded`.

**Comment by dougwilson** [comment]
Or, perhaps we can make that pluggable in here in some way.

**Comment by silverwind** [comment]
Now that I look at `forwarded`, it seems pretty barebone for my purpose. I was hoping for broader support for proxy headers other than `X-Forwarded-For`. Do intend to keep it lean and just support one header? If that's the case, I think I'm better of creating my own parser.

**Comment by dougwilson** [comment]
Yes, I think so. There was a long discussion about just this topic and how to design it over in the forwarded module, and I'll read it when I get home and catch myself back up on what the ideas were regarding that.

**Comment by silverwind** [comment]
I guess it makes sense to keep is lean for express if you can support 90% of the cases through a single header and I also guess most users aren't interested in logging the port. Probably best to keep my ideas out of it and create a separate module to support exotic proxies and ports.

**Comment by dougwilson** [comment]
Maybe this may appear one day here, but this issue is quite old now, and I don't have a need to work on a PR to add it, and doesn't seem like anyone so far is, either :) This can always be reopened if needed / a new issue can be created without it being a duplicate.
